config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root 'posts#index'
  get 'home/about'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sing_up) <<:name
  	devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :image, :name)
    end
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to post_path, notice: "You dont have permission to change that post" if @post.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
 <div class="container-fluid">
  <div class="navbar-header">
   <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
     </button>
     <%= link_to 'Little Violet Pony', root_path, class: 'navbar-brand' %>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
   <ul class="nav navbar-nav navbar-right">
      <%= link_to 'Main page', root_path, class: 'btn btn-warning ' %>
      <%= link_to 'About me', home_about_path, class: 'btn btn-info ' %>
      <%= link_to 'New post', new_post_path, class: 'btn btn-default ' %>
      <% if user_signed_in? %>
       <%=link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-primary ' %>
       <%=link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger ' %>
      <% else %>
       <%=link_to 'Login', new_user_session_path, class: 'btn btn-success ' %>
       <%=link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary ' %>
      <% end %>
   </ul>
  </div>
 </div>

app/views/home/about.html.erb
<div class="jumbotron">
 <h1>About me</h1>
 <p>Still learning!</p>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
 <h1>Welcome in my app!</h1>
 <p>Just few things there.. xd</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Guide</title>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
 <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'>
</head>
<body>
 <%= render 'home/header' %>
 <div class="container">
   <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
   <% end %>
  <%= yield %>
 </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: {multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, "Description" %><br>
    <%= f.text_field :description ,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image, "Image" %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit "Send image", class: 'btn btn-primary btn-lg'  %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id='posts' class='transitions-enabled'>
<% @posts.each do |post| %>
<div class='box'>
  <div class='panel panel-default'>
    <%=link_to image_tag(post.image.url(:medium)), post %><br/>
    <div class='panel-body'>
      <%= post.description %><br/>
      <br/><strong><%= post.user.name if post.user %></strong><br/>
    </div>
        <% if post.user == current_user %>
          <div class="panel-footer">
          <%= link_to 'Edit', edit_post_path(post) %><br/>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
<div class="center">
<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class='row'>
	<div class='col-md-offset-2 col-md-8'>
		<div class="panel panel-default">
 <div class='panel-header center'><%= image_tag @post.image.url(:medium) %></div>
 <div class='panel-body'>
  <%= @post.description %><br/>
<% if @post.user == current_user %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>
</div>
</div>
</div>
</div>